Traceback (most recent call last):
  File "/Users/ilja/Dropbox/ATBS/11_debugging.py", line 25, in <module>
    raise Exception('This is an error!!!')
Exception: This is an error!!!
